### ISSUE TITLE
Sometimes on scrolling down the contents starts rerending continously 

### ISSUE THREAD

**Issue by ansari9546** [NeXTs/Clusterize.js#176]
Sometimes on scrolling down the list the cluster starts re-render the data continously. Try to debug but when the console opens it mostly automatically fixed. And sometime from debugginf I find out that the cluster calculates the height and starts renders data continously. I loads data asynchrously and changes the states of data using cluster.update method. I don`t have fixed scenario for this. If anyone have solution please help me

**Comment by Ladvace** [comment]
does it start flickering?

**Comment by ansari9546** [comment]
Yes it does.

**Comment by Ladvace** [comment]
yeah also to me and I'm trying to figure out the problem

**Comment by ansari9546** [comment]
At this moment I have solved it for the time being to get the scroll event and on that basis I tried to refresh the cluster. Somehow this potential fix works for me

**Comment by Ladvace** [comment]
I will try

**Comment by Ladvace** [comment]
actually don't seems to working for me

**Comment by ansari9546** [comment]
cluster.getScrollProgress() helps me to tackle the issue to flicker. I used my logic further to detect whether it is flickering or not.

**Comment by Ladvace** [comment]
and when u detect it what did you do?

**Comment by Ladvace** [comment]
i tried using .getScrollProgress() but i just get an initial 0, if I scroll it doesn't change

**Comment by ansari9546** [comment]
use cluster.refresh() to solve the flickering

**Comment by ansari9546** [comment]
If the listing starts flickering then the getScrollProgress() will be called continously. Now whether you will get the same scrollIndex of fluctuated between 2-3 index values. when you get that simply refresh the cluster. It will solve the problem of flickering.

**Comment by Ladvace** [comment]
for me getScrollProgress()  is called just once

**Comment by FeehGb** [comment]
how did you fix it ?

**Comment by ansari9546** [comment]
I fixed it by using the getScrollProgress() if progress remains the same on getting the event then I call the custerize.refresh() event.
this trick works well for me

**Comment by FeehGb** [comment]
Can you show me in the code where did you put getScrollProgress to detect it.
Thanks

**Comment by NeXTs** [comment]
Hello guys
Could you provide a demo at codepen?

**Comment by ansari9546** [comment]
@FeehGb  you can use the below demo link that shows how I have tried to fix this issue.
[https://codepen.io/arsalanansari9546/pen/KKgajWa](https://codepen.io/arsalanansari9546/pen/KKgajWa)

**Comment by FeehGb** [comment]
thanks.
It will help me a lot.

**Comment by fmp777** [comment]
> @FeehGb you can use the below demo link that shows how I have tried to fix this issue. https://codepen.io/arsalanansari9546/pen/KKgajWa

With your patch, the flickering (rapid redrawing of content) stops, but i also end up with missing data/elements on page. ie: scroll down to bottom, then back to top and the top is missing. Also the bottom of list is missing if you scroll to bottom from top.

This seems like something that needs to be fixed internally, no?  I'm not quite clear what the actual problem is.

**Comment by FeehGb** [comment]
@fmp777 I fixed this problem. I set the fixed heigth for each element.
https://github.com/NeXTs/Clusterize.js/pull/181

**Comment by fmp777** [comment]
> @fmp777 I fixed this problem. I set the fixed heigth for each element. #181

Hmm, i've implemented your patch, and after setting a fixed height for each element, flicker gone, and no missing elements. 

Setting a fixed height is not ideal in many situations, i wonder if there's a way around that...

**Comment by HiveBotNoon** [comment]
This issue is not fixed for me even with the latest version. There are also some more issues that were not there before e.g. if the clusterize has more elements than "rows_in_block" it is not showing the elements at all, only after having called .refresh(true)

Any advice?

**Comment by NeXTs** [comment]
> yea the issue has reappeared - with no updates to Clusterize or other JS - must be a browser change that now brought this problem back

what browser? OS?
